### PR TITLE
Minor Navbar updates

### PR DESCRIPTION
**Pull request by that1matt**
Some minor code cleanup.

### CODE REVIEW

**Review by mattdarr — COMMENTED** [review]
@that1matt so this just adds labels to everything? Just want to make sure I didn't miss anything in the PR.

**Comment by that1matt** [comment]
> @that1matt so this just adds labels to everything? Just want to make sure I didn't miss anything in the PR.

@mattdarr yep, with some css prop changes from prop spreading on objects to arrays.

**Review by mattdarr — APPROVED** [review]

**Review by opaquejacob — APPROVED** [review]

**Review by opaquejacob — CHANGES_REQUESTED** [review]
Forgot to mention that version in `package.json` needs to be updated to `0.11.12`

**Comment by that1matt** [comment]
> Forgot to mention that version in `package.json` needs to be updated to `0.11.12`

Thanks, updated the version number.

**Review by opaquejacob — APPROVED** [review]

**Pull request merged**
